services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  wagtail:
    build: 
      context: .
      args:
        REQ_DIR: "requirements/"
        REQ_TXT: "prod.txt"
    image: kojamad28/postgres-wagtail
    container_name: wagtail
    command: /bin/bash
    volumes:
     - .:/usr/src
    tty: true
    stdin_open: true
    depends_on:
      - postgres
  nginx:
    image: kojamad28/wagtail-nginx
    container_name: nginx
    build: ./nginx
    volumes:
      - ./static:/usr/src/static
      - ./media:/usr/src/media
    ports:
      - "80:80"
    depends_on:
      - wagtail

volumes:
  postgres_data:
